### ISSUE TITLE
Error fetching Siku Fan 192.168.###.## data: Connection to Siku Fan failed: timed out

### ISSUE THREAD

**Issue by JoJoJo2211** [hmn/siku-integration#105]
## System Information

version | core-2024.10.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4994
Installed Version | 2.0.1
Stage | running
Available Repositories | 1526
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 28. April 2025 um 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-9.ui.nabu.casa
certificate_status | ready
instance_id | 18101094b09a4ea894036440f1c9859b
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 468.7 GB
disk_used | 16.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), Zigbee2MQTT (1.40.2-1), Studio Code Server (5.17.2), File editor (5.8.0), ESPHome (2024.10.2), AppDaemon (0.16.7), Grafana (10.1.3), Node-RED (18.1.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 2
views | 25
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 23. Oktober 2024 um 08:38
-- | --
current_recorder_run | 31. Oktober 2024 um 20:37
estimated_db_size | 1124.46 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/hmn/siku-integration/issues?q=is%3Aissue+label%3A%22Bug%22+)..

#### The error message is from yesterday, the debug log is from today. I hope that's not a problem. But the error occurs consistently. Debug logging is now still turned on. There should also be another error in the log regarding this integration. I will open a second post regarding this.

Logger: custom_components.siku.coordinator
Quelle: helpers/update_coordinator.py:386
Integration: Siku Fan ([Dokumentation](https://github.com/hmn/siku-integration), [Probleme](https://github.com/hmn/siku-integration/issues))
Erstmals aufgetreten: 31. Oktober 2024 um 20:39:44 (140 Vorkommnisse)
Zuletzt protokolliert: 10:14:09

Error fetching Siku Fan 192.###.###.51 data: Connection to Siku Fan failed: timed out
Error fetching Siku Fan 192.###.###.52 data: Connection to Siku Fan failed: timed out
Error fetching Siku Fan 192.###.###.55 data: Connection to Siku Fan failed: timed out
Error fetching Siku Fan 192.###.###.54 data: Connection to Siku Fan failed: timed out
Error fetching Siku Fan 192.###.###.56 data: Connection to Siku Fan failed: timed out
Error fetching Siku Fan 192.###.###.53 data: Connection to Siku Fan failed: timed out

### Reproduction steps

I didn't do anything, the error has been occurring since I set up the devices

### Debug logs

```text
See file stored under diagnostic dump. Unfortunately the protocol has over 620,000 characters
```

### Diagnostics dump

[2024-11-01_Debug-Log_SIKU Integration.txt](https://github.com/user-attachments/files/17598431/2024-11-01_Debug-Log_SIKU.Integration.txt)

**Comment by hmn** [comment]
as fr as I can see it must be somthing related to your fans or network, because the packet generated looks ok, and other calls with the same data seems to work

```
2024-11-01 10:34:58.280 ERROR (MainThread) [custom_components.siku.coordinator] Error fetching Siku Fan 192.168.17.52 data: Connection to Siku Fan failed: timed out
2024-11-01 10:34:58.280 DEBUG (MainThread) [custom_components.siku.coordinator] Finished fetching Siku Fan 192.168.17.52 data in 10.011 seconds (success: False)

```

the timeout is 10 seconds in the current version, and have been set to 1 sec in the new beta to resolve network errors faster

so you could try updating to the v2.2.0-beta.2 version

https://github.com/hmn/siku-integration/releases/tag/v2.2.0-beta.2

**Comment by JoJoJo2211** [comment]
Sorry for my late reply. I have installed the beta and now also the new official version 2.2.0. Unfortunately the problem is still not gone. After updating the official version, other errors also occurred. Should I list them here or submit a new request?

**Comment by hmn** [comment]
I need new logs and new incidents, but if you get timeout errors it's pretty hard for me to fix, they run UDP so any inconsistency in wifi seems to have a big impact on timeout errors

**Comment by JoJoJo2211** [comment]
I have attached another debug log. The error occurs at 18:12:24. So my WiFi is actually very stable. The network coverage is also great. Would it possibly help if I let automations execute commands at a longer interval? I now always have a delay of one second? So e.g. Switch on the fan - one second delay - set the fan to heat recovery - one second delay - change the fan speed

[2024-11-09_DEBUG Protokoll_SIKU_2.txt](https://github.com/user-attachments/files/17688787/2024-11-09_DEBUG.Protokoll_SIKU_2.txt)
