### ISSUE TITLE
V2.2 broke manual % setting on Duka One S6 Plus Wifi

### ISSUE THREAD

**Issue by kindred40** [hmn/siku-integration#109]
## System Information

version | core-2024.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.54-haos
arch | x86_64
timezone | Europe/Oslo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4592
Installed Version | 2.0.1
Stage | running
Available Repositories | 1463
Downloaded Repositories | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Easee EV Charger</summary>

component_version | 0.9.64
-- | --
reach_easee_cloud | ok
connected2stream | true

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.2
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 30.8 GB
disk_used | 19.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), Cloudflared (5.2.1), Studio Code Server (5.17.3), ESPHome (2024.10.3), Advanced SSH & Web Terminal (19.0.0), TasmoAdmin (0.30.6), EMHASS (v0.11.2), Zigbee2MQTT (1.41.0-1), Music Assistant Server (2.3.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 11
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 2, 2024 at 10:53
-- | --
current_recorder_run | November 9, 2024 at 10:27
estimated_db_size | 1088.59 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Sonoff</summary>

version | 3.8.1 (ffa7e22)
-- | --
cloud_online | 1 / 2
local_online | 1 / 1

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/hmn/siku-integration/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After update i get an error trying to set fan speed to low/medium/high (33/66/100%)
Also can't set direction forward/reverse.

All sensors are working but any settings fail.

This is using the Hacks integration in HA.
Version 2.1 is working.

### Reproduction steps

1. Install update
2.reboot
3. Install fan
4. Try any settings and it gives you an error
...

### Debug logs

```text
Later
```

**Comment by JoJoJo2211** [comment]
I have the same problem after the update to v2.2.0

**Comment by hmn** [comment]
I don't have a v2 fan so I need a debug log to help

**Comment by JoJoJo2211** [comment]
[2024-11-09_DEBUG Protokoll_SIKU.txt](https://github.com/user-attachments/files/17688726/2024-11-09_DEBUG.Protokoll_SIKU.txt)

here is my debug log

**Comment by JoJoJo2211** [comment]
[2023-06-14_BDA_Anschluss_SmartHome_RV_V2.pdf](https://github.com/user-attachments/files/17688728/2023-06-14_BDA_Anschluss_SmartHome_RV_V2.pdf)

I have another document from the seller here, it might also be of interest to you. Unfortunately it is mostly in German...

**Comment by JoJoJo2211** [comment]
What I also noticed is that all sensors (speed, humidity, filter timer, boost mode, mode, alarm) of two of my six fans no longer show a status. the status is unknown. The status of the sensors is still displayed for the other four fans.

**Comment by hmn** [comment]
@JoJoJo2211 

I might have fixed the manual fan support, but I can't test it so could you try out v2.2.1-beta1 and attach a debug log with the results

**Comment by JoJoJo2211** [comment]
[2024-11-09_DEBUG Protokoll_SIKU_3.txt](https://github.com/user-attachments/files/17688920/2024-11-09_DEBUG.Protokoll_SIKU_3.txt)

So now there aren't even any buttons to choose a speed? I also see directly on the device that this entity is no longer provided by the integration?

**Comment by hmn** [comment]
There were a varialbe reference error, try v2.2.1-beta2

**Comment by JoJoJo2211** [comment]
I think it's working now. I can choose all speeds, the sensors can also be seen.
This is the only error I see now:

Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:245
Integration: Home Assistant WebSocket API ([Dokumentation](https://www.home-assistant.io/integrations/websocket_api), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
Erstmals aufgetreten: 19:43:14 (1 Vorkommnisse)
Zuletzt protokolliert: 19:43:14

[140001005266704] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/siku/fan.py", line 105, in async_set_percentage
    await self.coordinator.api.power_on()
  File "/config/custom_components/siku/api_v2.py", line 120, in power_on
    await self._send_command(FUNC_READ_WRITE, cmd)
  File "/config/custom_components/siku/api_v2.py", line 241, in _send_command
    result_data, server = s.recvfrom(256)
                          ^^^^^^^^^^^^^^^
TimeoutError: timed out

**Comment by hmn** [comment]
@kindred40 thanks a lot for the test host it helped a lot in identifying some of the wierdness in the v2 api dok

v2.2.1 should now work better and reset filter timer should work without it generating timout errors
