### ISSUE TITLE
Humidity sensor

### ISSUE THREAD

**Issue by joimaggz** [hmn/siku-integration#90]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/hmn/siku-integration/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

First off thank you for this great integration. Works like a charm. Currently it is missing reading data from the humidity sensor. It would be great to have that as well.

### Describe the solution you'd like

Get current humidity percentage value from the humidity sensor.

### Describe alternatives you've considered

I currently use dingusdk/ha-dukaone to get the humidity value. It is another integration for similar fans, but that one lacks some controls that your integration has. 

### Additional context

Possible to look at dingus/ha-dukaone to figure out how to get the data. Thanks again!

**Comment by hmn** [comment]
I created this beta release you can test https://github.com/hmn/siku-integration/releases/tag/v2.1.0-beta.1

**Comment by joimaggz** [comment]
@hmn  That worked like a charm! No bugs in the logger. I will write back a bit later regarding stability or any issues. I havent installed the fans yet so will be some days before.

Thank you for spending the time to implement this feature even though its not of use for you! I really tried to do it myself, it didnt work, but the good thing that came out of it is that I learned a tiny fraction of coding :)

My fan is V.3 - as I understand there is no difference from V.3 and V.2 when it comes to integration compatability. The product I am using is called Twinfresh (www.twinfresh.no) so you can add it to the list of compatable products if you want.

<img width="506" alt="Screenshot 2024-03-30 at 00 05 01" src="https://github.com/hmn/siku-integration/assets/110853319/f48863ac-9094-44a6-8756-d2290c1d9ea2">

**Comment by victori3d** [comment]
@hmn: I tested the integration as well. It works really well. Thanks a lot for enhancing the software.
