### ISSUE TITLE
Reset of Filter Alarm

### ISSUE THREAD

**Issue by Milbo001** [hmn/siku-integration#96]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/hmn/siku-integration/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Thank you very muchfor this great integration. Works great in my setup. 
So far the only feature I'm missing is to reset both general alarm and filter alarm direct from HA.

### Describe the solution you'd like

Be able to configure a simple "Edge" switch (Changes state on every hit) to reset the general alarm and filter alarm.

### Describe alternatives you've considered

I have been using "dingusdk/ha-dukaone" integration, which has the possibility, but I find this integration much more stable and better control options for my setup.

### Additional context

Possible to look at "dingus/ha-dukaone" to figure out how to get the data. Thanks again!

**Comment by hmn** [comment]
I created support for filter reset via a button in the integration, but I don't have a v2 fan so I can't test it

You can try downloading the beta release at see if it works 

https://github.com/hmn/siku-integration/releases/tag/v2.2.0-beta.1

**Comment by Milbo001** [comment]
Will have a test run, when back Home from vacation and report back. Thank you.

**Comment by Milbo001** [comment]
First, Thank you, for the great work and sorry for delay in testing, but had issues with my HA installation and had to rebuild some of it!
Today I updated to release V2.2.1 and find the reset function working as expected. I was wondering if a alarm reset also would be possible to add in a future release?
Keep up the great work, it is much appreciated.
